blank_issues_enabled: false
contact_links:
  - name: 📃 Documentation
    url: https://github.com/LuisCupul04/ExtenRe-documentation/
    about: Don't know how or where to start? Check out our documentation!